services:
  # 1. Free Redis Instance (For caching or future worker use)
  - type: redis
    name: incidentflow-redis
    ipAllowList: [] 
    plan: free

  # 2. Free FastAPI Web Service
  - type: web
    name: incidentflow-api
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: incidentflow-redis
          property: connectionString
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: MAILJET_API_KEY
        sync: false
      - key: MAILJET_API_SECRET
        sync: false
      - key: MAILJET_SENDER_EMAIL
        sync: false