"""Initial migration

Revision ID: 02678662c6cc
Revises: 
Create Date: 2026-02-03 21:57:55.524727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02678662c6cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incident_events', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('incident_events', 'old_value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('incident_events', 'new_value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('incidents', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('incidents', 'severity',
               existing_type=postgresql.ENUM('SEV1', 'SEV2', 'SEV3', 'SEV4', name='incident_severity'),
               type_=sa.Enum('SEV1', 'SEV2', 'SEV3', 'SEV4', name='incidentseverity'),
               existing_nullable=False)
    op.alter_column('incidents', 'status',
               existing_type=postgresql.ENUM('DETECTED', 'INVESTIGATING', 'MITIGATED', 'RESOLVED', 'POSTMORTEM', 'CLOSED', 'ESCALATED', name='incident_status'),
               type_=sa.Enum('DETECTED', 'INVESTIGATING', 'MITIGATED', 'RESOLVED', 'POSTMORTEM', 'CLOSED', 'ESCALATED', name='incidentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'DETECTED'::incident_status"))
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ENGINEER', 'MANAGER', 'ADMIN', 'BOT', name='user_role'),
               type_=sa.Enum('ENGINEER', 'MANAGER', 'ADMIN', 'BOT', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'ENGINEER'::user_role"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ENGINEER', 'MANAGER', 'ADMIN', 'BOT', name='userrole'),
               type_=postgresql.ENUM('ENGINEER', 'MANAGER', 'ADMIN', 'BOT', name='user_role'),
               existing_nullable=False,
               existing_server_default=sa.text("'ENGINEER'::user_role"))
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('incidents', 'status',
               existing_type=sa.Enum('DETECTED', 'INVESTIGATING', 'MITIGATED', 'RESOLVED', 'POSTMORTEM', 'CLOSED', 'ESCALATED', name='incidentstatus'),
               type_=postgresql.ENUM('DETECTED', 'INVESTIGATING', 'MITIGATED', 'RESOLVED', 'POSTMORTEM', 'CLOSED', 'ESCALATED', name='incident_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'DETECTED'::incident_status"))
    op.alter_column('incidents', 'severity',
               existing_type=sa.Enum('SEV1', 'SEV2', 'SEV3', 'SEV4', name='incidentseverity'),
               type_=postgresql.ENUM('SEV1', 'SEV2', 'SEV3', 'SEV4', name='incident_severity'),
               existing_nullable=False)
    op.alter_column('incidents', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('incident_events', 'new_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incident_events', 'old_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incident_events', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
