"""add organizations and backfill

Revision ID: 0ca9eb758cb9
Revises: d6edd2ddcad7
Create Date: 2026-02-03 23:11:08.594215

"""
from typing import Sequence, Union

from uuid import UUID

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = '0ca9eb758cb9'
down_revision: Union[str, Sequence[str], None] = 'd6edd2ddcad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create the organizations table
    op.create_table('organizations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug')
    )

    # 2. Add the columns to existing tables (Nullable initially)
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('incidents', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('incident_events', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('incident_attachments', sa.Column('organization_id', sa.UUID(), nullable=True))

    # 3. Create Foreign Key Constraints
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'incidents', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'incident_events', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'incident_attachments', 'organizations', ['organization_id'], ['id'])

    # --- DATA MIGRATION START ---
    
    # 4. Create the Default "HQ" Organization
    connection = op.get_bind()
    
    # Generate a static UUID so we can reference it
    hq_org_id = UUID("00000000-0000-0000-0000-000000000111")
    
    print(f"Creating default Organization with ID: {hq_org_id}")
    
    # Insert HQ
    connection.execute(
        text("INSERT INTO organizations (id, name, slug, created_at) VALUES (:id, :name, :slug, NOW())"),
        {"id": hq_org_id, "name": "Headquarters", "slug": "hq"}
    )
    
    # 5. Assign ALL existing data to this HQ ID
    print("Assigning existing Users to HQ...")
    connection.execute(
        text("UPDATE users SET organization_id = :org_id WHERE organization_id IS NULL"),
        {"org_id": hq_org_id}
    )
    
    print("Assigning existing Incidents to HQ...")
    connection.execute(
        text("UPDATE incidents SET organization_id = :org_id WHERE organization_id IS NULL"),
        {"org_id": hq_org_id}
    )
    
    print("Assigning events and attachments to HQ...")
    connection.execute(
        text("UPDATE incident_events SET organization_id = :org_id WHERE organization_id IS NULL"),
        {"org_id": hq_org_id}
    )
    connection.execute(
        text("UPDATE incident_attachments SET organization_id = :org_id WHERE organization_id IS NULL"),
        {"org_id": hq_org_id}
    )
    
    # --- DATA MIGRATION END ---
    
    # 6. Now that data exists, alter columns to be NOT NULL
    op.alter_column('users', 'organization_id', nullable=False)
    op.alter_column('incidents', 'organization_id', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.alter_column('incidents', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('incidents', 'organization_id')
    op.drop_constraint(None, 'incident_events', type_='foreignkey')
    op.alter_column('incident_events', 'new_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incident_events', 'old_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incident_events', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('incident_events', 'organization_id')
    op.drop_constraint(None, 'incident_attachments', type_='foreignkey')
    op.drop_column('incident_attachments', 'organization_id')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
