"""remove default id

Revision ID: 2b1911bc8543
Revises: 
Create Date: 2026-02-18 15:16:29.632535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1911bc8543'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Create the organizations table first
    op.create_table('organizations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('slug', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    
    # 2. Seed the Default Org
    op.execute("""
        INSERT INTO organizations (id, name, slug) 
        VALUES ('00000000-0000-0000-0000-000000000111', 'Default Org', 'default-org')
        ON CONFLICT (id) DO NOTHING
    """)

    # 3. Handle incident_events
    op.add_column('incident_events', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute("UPDATE incident_events SET organization_id = '00000000-0000-0000-0000-000000000111' WHERE organization_id IS NULL")
    op.alter_column('incident_events', 'organization_id', nullable=False)
    op.create_foreign_key(None, 'incident_events', 'organizations', ['organization_id'], ['id'])

    # 4. Handle incidents (THIS IS WHERE IT FAILED RECENTLY)
    op.add_column('incidents', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute("UPDATE incidents SET organization_id = '00000000-0000-0000-0000-000000000111' WHERE organization_id IS NULL")
    op.alter_column('incidents', 'organization_id', nullable=False)
    op.create_foreign_key(None, 'incidents', 'organizations', ['organization_id'], ['id'])

    # 5. Handle users
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.execute("UPDATE users SET organization_id = '00000000-0000-0000-0000-000000000111' WHERE organization_id IS NULL")
    op.alter_column('users', 'organization_id', nullable=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])

    # 6. Create attachments table (Safe because it's new)
    op.create_table('incident_attachments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('incident_id', sa.UUID(), nullable=False),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('file_key', sa.String(), nullable=False),
        sa.Column('uploaded_by', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_key')
    )

    # 7. Apply the remaining type changes (Alembic's cleanup)
    op.alter_column('incident_events', 'event_type', existing_type=sa.TEXT(), type_=sa.String())
    op.alter_column('incident_events', 'old_value', existing_type=sa.TEXT(), type_=sa.String())
    op.alter_column('incident_events', 'new_value', existing_type=sa.TEXT(), type_=sa.String())
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('incidents', 'title', existing_type=sa.TEXT(), type_=sa.String())
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('users', 'email', existing_type=sa.TEXT(), type_=sa.String())
    op.alter_column('users', 'full_name', existing_type=sa.TEXT(), type_=sa.String())

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'phone_number')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.alter_column('incidents', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('incidents', 'organization_id')
    op.drop_column('incidents', 'resolved_at')
    op.drop_constraint(None, 'incident_events', type_='foreignkey')
    op.alter_column('incident_events', 'new_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incident_events', 'old_value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incident_events', 'event_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('incident_events', 'organization_id')
    op.drop_table('incident_attachments')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
